version: '3.9'

services:
  mysql:
    image: mysql:9.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cloud_db
      MYSQL_USER: cloud_user
      MYSQL_PASSWORD: cloud_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # 使用 init 脚本初始化数据库,而不是默认文件夹方式
    # - ./inits/db:/docker-entrypoint-initdb.d
    networks:
      - cloud-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  db-init:
    image: mysql:9.4   # 还是用 MySQL 镜像跑初始化脚本
    environment:
      MYSQL_ROOT_PASSWORD: root123
      NACOS_VERSION: master   # 默认 master 对应 github 分支的名称
      SEATA_VERSION: 2.x      # 默认 2.x 分支 对应 github 分支的名称
    volumes:
      - ./inits/script/init-db.sh:/init-db.sh      # 改脚本名更通用
      - ./inits/db:/project-init-scripts           # 里面可以放 nacos-mysql.sql / seata-mysql.sql
    command: /bin/bash /init-db.sh
    networks:
      - cloud-network
    depends_on:
      - mysql


  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis123
    networks:
      - cloud-network

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-server
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
      NACOS_CONFIG_GRAY_MIGRATE: "false"
      NACOS_CORE_API_COMPATIBILITY_CONSOLE_ENABLED: "true"
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "8080:8080"
    volumes:
      - nacos_data:/home/nacos/data
      - nacos_logs:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    depends_on:
      - db-init
      - mysql
    restart: always
    networks:
      - cloud-network

  sentinel:
    build: ./Sentinel
    container_name: sentinel-dashboard
    ports:
      - "8888:8080"
    networks:
      - cloud-network
    depends_on:
      - nacos
    restart: always

  seata:
    image: seataio/seata-server:2.0.0
    container_name: seata-server
    ports:
      - "8091:8091"  # 映射到容器内的 8091 端口
      - "7091:7091"
    volumes:
      - ./seata/config/file.conf:/seata-server/resources/file.conf
      - ./seata/config/registry.conf:/seata-server/resources/registry.conf
    networks:
      - cloud-network
    depends_on:
      - mysql
      - db-init
#    restart: always

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  nacos_data:
    driver: local
  nacos_logs:
    driver: local

networks:
  cloud-network:
    driver: bridge